#
# Copyright 2019-2023 Nestybox, Inc.
#

#
# Docker image for deploying Sysbox-CE on a K8s host.
#
# Build with:
#
# docker build -t nestybox/sysbox-deploy-k8s .
#

# Note: we use a centos base image because it carries a systemctl that can
# communicate with the host's systemd via dbus. This does not work when using a
# ubuntu + systemd image (systemctl can't not connect to the host's dbus, even
# though the host's dbus socket was mounted into the container).

FROM ghcr.io/nestybox/centos7/systemd

ARG sys_arch
ENV SYS_ARCH=${sys_arch}
ARG sysbox_version
ENV SYSBOX_VERSION=${sysbox_version}

ARG DEST=/opt/sysbox
ARG CRICTL_VERSION="v1.33.0"
ARG CRIO_V1_29_TAR="cri-o.${SYS_ARCH}.v1.29.0.tar.gz"
ARG CRIO_V1_30_TAR="cri-o.${SYS_ARCH}.v1.30.0.tar.gz"
ARG CRIO_V1_31_TAR="cri-o.${SYS_ARCH}.v1.31.0.tar.gz"
ARG CRIO_V1_32_TAR="cri-o.${SYS_ARCH}.v1.32.0.tar.gz"
ARG CRIO_V1_33_TAR="cri-o.${SYS_ARCH}.v1.33.0.tar.gz"

RUN sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-* \
    && sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*

RUN yum install -y curl wget git bc which epel-release \
    && yum install -y jq

RUN curl -Lso /bin/kubectl https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/${SYS_ARCH}/kubectl && \
    chmod +x /bin/kubectl

RUN wget https://github.com/TomWright/dasel/releases/download/v1.27.3/dasel_linux_${SYS_ARCH} \
    && mv dasel_linux_${SYS_ARCH} dasel && chmod +x dasel && mv ./dasel /usr/local/bin/dasel

# crictl will be copied to the host, and used by the crio installation agents
RUN wget https://github.com/kubernetes-sigs/cri-tools/releases/download/${CRICTL_VERSION}/crictl-${CRICTL_VERSION}-linux-${SYS_ARCH}.tar.gz \
    && tar zxvf crictl-${CRICTL_VERSION}-linux-${SYS_ARCH}.tar.gz -C /usr/local/bin \
    && chmod +x /usr/local/bin/crictl \
    && rm -f crictl-${CRICTL_VERSION}-linux-${SYS_ARCH}.tar.gz

# shiftfs-dkms sources
RUN git clone --branch k5.4 https://github.com/nestybox/shiftfs-dkms.git /opt/shiftfs-k5.4 \
    && git clone --branch k5.10 https://github.com/nestybox/shiftfs-dkms.git /opt/shiftfs-k5.10 \
    && git clone --branch k5.11 https://github.com/nestybox/shiftfs-dkms.git /opt/shiftfs-k5.11 \
    && git clone --branch k5.13 https://github.com/nestybox/shiftfs-dkms.git /opt/shiftfs-k5.13 \
    && git clone --branch k5.16 https://github.com/nestybox/shiftfs-dkms.git /opt/shiftfs-k5.16 \
    && git clone --branch k5.17 https://github.com/nestybox/shiftfs-dkms.git /opt/shiftfs-k5.17 \
    && git clone --branch k5.18 https://github.com/nestybox/shiftfs-dkms.git /opt/shiftfs-k5.18 \
    && git clone --branch k6.1 https://github.com/nestybox/shiftfs-dkms.git /opt/shiftfs-k6.1

#
# Load Sysbox installation artifacts
#

COPY bin/sysbox-ce /opt/sysbox/bin

COPY systemd/50-sysbox-mod.conf /opt/sysbox/systemd/50-sysbox-mod.conf
COPY systemd/99-sysbox-sysctl.conf /opt/sysbox/systemd/99-sysbox-sysctl.conf
COPY systemd/sysbox-installer-helper.service /opt/sysbox/systemd/sysbox-installer-helper.service
COPY systemd/sysbox-removal-helper.service /opt/sysbox/systemd/sysbox-removal-helper.service
COPY systemd/sysbox-fs.service /opt/sysbox/systemd/sysbox-fs.service
COPY systemd/sysbox-mgr.service /opt/sysbox/systemd/sysbox-mgr.service
COPY systemd/sysbox.service /opt/sysbox/systemd/sysbox.service

COPY scripts/sysbox-deploy-k8s.sh /opt/sysbox/scripts/sysbox-deploy-k8s.sh
COPY scripts/sysbox-installer-helper.sh /opt/sysbox/scripts/sysbox-installer-helper.sh
COPY scripts/sysbox-removal-helper.sh /opt/sysbox/scripts/sysbox-removal-helper.sh

#
# Load CRI-O installation artifacts
#

RUN wget https://storage.googleapis.com/cri-o/artifacts/${CRIO_V1_29_TAR} -O cri-o.${SYS_ARCH}.tar.gz \
    && mkdir -p /opt/crio-deploy/bin/v1.29 \
    && mv cri-o.${SYS_ARCH}.tar.gz /opt/crio-deploy/bin/v1.29/.

RUN wget https://storage.googleapis.com/cri-o/artifacts/${CRIO_V1_30_TAR} -O cri-o.${SYS_ARCH}.tar.gz \
    && mkdir -p /opt/crio-deploy/bin/v1.30 \
    && mv cri-o.${SYS_ARCH}.tar.gz /opt/crio-deploy/bin/v1.30/.

RUN wget https://storage.googleapis.com/cri-o/artifacts/${CRIO_V1_31_TAR} -O cri-o.${SYS_ARCH}.tar.gz \
    && mkdir -p /opt/crio-deploy/bin/v1.31 \
    && mv cri-o.${SYS_ARCH}.tar.gz /opt/crio-deploy/bin/v1.31/.

RUN wget https://storage.googleapis.com/cri-o/artifacts/${CRIO_V1_32_TAR} -O cri-o.${SYS_ARCH}.tar.gz \
    && mkdir -p /opt/crio-deploy/bin/v1.32 \
    && mv cri-o.${SYS_ARCH}.tar.gz /opt/crio-deploy/bin/v1.32/.

RUN wget https://storage.googleapis.com/cri-o/artifacts/${CRIO_V1_33_TAR} -O cri-o.${SYS_ARCH}.tar.gz \
    && mkdir -p /opt/crio-deploy/bin/v1.33 \
    && mv cri-o.${SYS_ARCH}.tar.gz /opt/crio-deploy/bin/v1.33/.

COPY systemd/crio-installer.service /opt/crio-deploy/systemd/crio-installer.service
COPY systemd/crio-removal.service /opt/crio-deploy/systemd/crio-removal.service
COPY scripts/crio-extractor.sh /opt/crio-deploy/scripts/crio-extractor.sh

COPY scripts/crio-installer.sh /opt/crio-deploy/scripts/crio-installer.sh
COPY scripts/crio-removal.sh /opt/crio-deploy/scripts/crio-removal.sh

COPY systemd/kubelet-config-helper.service /opt/crio-deploy/systemd/kubelet-config-helper.service
COPY scripts/kubelet-config-helper.sh /opt/crio-deploy/scripts/kubelet-config-helper.sh

COPY systemd/kubelet-unconfig-helper.service /opt/crio-deploy/systemd/kubelet-unconfig-helper.service
COPY scripts/kubelet-unconfig-helper.sh /opt/crio-deploy/scripts/kubelet-unconfig-helper.sh

COPY config/crio-kubelet-options /opt/crio-deploy/config/crio-kubelet-options
COPY config/etc_cni_net.d_200-loopback.conf /opt/crio-deploy/config/etc_cni_net.d_200-loopback.conf
COPY config/etc_containers_registries.conf.d_000-shortnames.conf /opt/crio-deploy/config/etc_containers_registries.conf.d_000-shortnames.conf
COPY config/etc_containers_storage.conf /opt/crio-deploy/config/etc_containers_storage.conf
COPY config/etc_containers_registries.conf /opt/crio-deploy/config/etc_containers_registries.conf
COPY config/etc_containers_policy.json /opt/crio-deploy/config/etc_containers_policy.json
COPY config/etc_containers_registries.d_default.yaml /opt/crio-deploy/config/etc_containers_registries.d_default.yaml

#
# Load CRI-O patched binaries (to generate correct user-ns mappings)
#

COPY bin/crio/v1.29/crio /opt/crio-deploy/bin/v1.29/crio-patched
COPY bin/crio/v1.30/crio /opt/crio-deploy/bin/v1.30/crio-patched
COPY bin/crio/v1.31/crio /opt/crio-deploy/bin/v1.31/crio-patched
COPY bin/crio/v1.32/crio /opt/crio-deploy/bin/v1.32/crio-patched
COPY bin/crio/v1.33/crio /opt/crio-deploy/bin/v1.33/crio-patched

COPY bin/crio/v1.29/pinns /opt/crio-deploy/bin/v1.29/pinns-patched
COPY bin/crio/v1.30/pinns /opt/crio-deploy/bin/v1.30/pinns-patched
COPY bin/crio/v1.31/pinns /opt/crio-deploy/bin/v1.31/pinns-patched
COPY bin/crio/v1.32/pinns /opt/crio-deploy/bin/v1.32/pinns-patched
COPY bin/crio/v1.33/pinns /opt/crio-deploy/bin/v1.33/pinns-patched
